name: Build and deploy Node.js app to Azure Web App - simplechatapp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./Real-Time-Chat-App/server # Update this path if needed

    - name: Build project
      run: npm run build --if-present
      working-directory: ./Real-Time-Chat-App/server # Update this path if needed


    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: simplechatapp
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .